# Generated by Django 3.1 on 2020-08-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
